image: docker:latest

services:
  - docker:dind

variables:
  # see https://gitlab.com/gitlab-org/gitlab-ce/issues/17861#note_12991518
  DOCKER_DRIVER: overlay

stages:
  - build
  - deploy

variables:
  HEROKU_USER_NAME: _
  HEROKU_REGISTRY: registry.heroku.com

before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose
  - docker-compose --version
  # convert / to -, remove # character from docker tag name to make it a valid name
  - export IMG_TAG=`if [ "$CI_BUILD_REF_NAME" == "master" ]; then echo "latest"; else echo $CI_BUILD_REF_NAME | sed -e 's/[\/]/-/g' | sed -e 's/[\#]//g'; fi`
  - export DOCKER_IMAGE_PROD=$CI_REGISTRY_IMAGE:$IMG_TAG
  - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
  - export CI_BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  - export CI_BUILDER=gitlab-ci

build-verify:
  stage: build
  script:
    - docker-compose run --rm dev yarn
    # run and check the dev container
    # build, run and check the prod image
    - docker-compose run --rm dev yarn run build
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml build prod
    - docker push $DOCKER_IMAGE_PROD

deploy-staging-gcp:
  image: google/cloud-sdk
  stage: deploy
  before_script:
    - apt-get install -yq gettext # install envsubst
    # - chmod +x ./scripts/export_deploy_environments.sh
    # - . ./scripts/export_deploy_environments.sh
    # convert / to -, remove # character from docker tag name to make it a valid name
    - export IMG_TAG=`if [ "$CI_BUILD_REF_NAME" == "master" ]; then echo "latest"; else echo $CI_BUILD_REF_NAME | sed -e 's/[\/]/-/g' | sed -e 's/[\#]//g'; fi`
    - export DOCKER_IMAGE_PROD=$CI_REGISTRY_IMAGE:$IMG_TAG
    - export GCP_IMAGE=$DOCKER_IMAGE_PROD
    - export GCP_PROJECT_ID=$GCP_PROJECT_ID_STAGING
    #- docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - echo $GCP_KEY_FILE_STAGING > /tmp/gcp_key_file.json
    - export DEPLOYED_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  script:
    - envsubst <k8s/deployment_staging.tpl.yaml >k8s/deployment.yaml
    - sh scripts/deploy_gcp.sh
  after_script:
    - rm /tmp/gcp_key_file.json
    - rm k8s/deployment.yaml
  environment: staging
  only:
    - develop
  allow_failure: true # for downstream failure
  when: on_success


deploy-prod-gcp:
  image: google/cloud-sdk
  stage: deploy
  before_script:
    - apt-get install -yq gettext # install envsubst
    # - chmod +x ./scripts/export_deploy_environments.sh
    # - . ./scripts/export_deploy_environments.sh
    # convert / to -, remove # character from docker tag name to make it a valid name
    - export IMG_TAG=`if [ "$CI_BUILD_REF_NAME" == "master" ]; then echo "latest"; else echo $CI_BUILD_REF_NAME | sed -e 's/[\/]/-/g' | sed -e 's/[\#]//g'; fi`
    - export DOCKER_IMAGE_PROD=$CI_REGISTRY_IMAGE:$IMG_TAG
    - export GCP_IMAGE=$DOCKER_IMAGE_PROD
    - export GCP_PROJECT_ID=$GCP_PROJECT_ID_STAGING
    #- docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - echo $GCP_KEY_FILE_STAGING > /tmp/gcp_key_file.json
    - export DEPLOYED_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  script:
    - envsubst <k8s/deployment_prod.tpl.yaml >k8s/deployment.yaml
    - sh scripts/deploy_gcp.sh
  after_script:
    - rm /tmp/gcp_key_file.json
    - rm k8s/deployment.yaml
  environment: prod
  only:
    - master
  allow_failure: true # for downstream failure
  when: on_success


deploy-staging-heroku:
  stage: deploy
  before_script:
    # convert / to -, remove # character from docker tag name to make it a valid name
    - export IMG_TAG=`if [ "$CI_BUILD_REF_NAME" == "master" ]; then echo "latest"; else echo $CI_BUILD_REF_NAME | sed -e 's/[\/]/-/g' | sed -e 's/[\#]//g'; fi`
    - export DOCKER_IMAGE=$CI_REGISTRY_IMAGE:$IMG_TAG
    - export HEROKU_IMAGE=$HEROKU_REGISTRY/$HEROKU_STAGING_APP_NAME/web
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker login --username=$HEROKU_USER_NAME --password=$HEROKU_STAGING_API_KEY $HEROKU_REGISTRY
  script:
    - sh scripts/deploy_heroku.sh
  environment: staging
  only:
    - develop
  allow_failure: true # for downstream failure
  when: on_success

deploy-prod-heroku:
  stage: deploy
  before_script:
    # convert / to -, remove # character from docker tag name to make it a valid name
    - export IMG_TAG=`if [ "$CI_BUILD_REF_NAME" == "master" ]; then echo "latest"; else echo $CI_BUILD_REF_NAME | sed -e 's/[\/]/-/g' | sed -e 's/[\#]//g'; fi`
    - export DOCKER_IMAGE=$CI_REGISTRY_IMAGE:$IMG_TAG
    - export HEROKU_IMAGE=$HEROKU_REGISTRY/$HEROKU_PROD_APP_NAME/web
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker login --username=$HEROKU_USER_NAME --password=$HEROKU_PROD_API_KEY $HEROKU_REGISTRY
  script:
    - sh scripts/deploy_heroku.sh
  environment: prod
  only:
    - master
  allow_failure: true # for downstream failure
  when: on_success
