version: '3'

services:

  prod:
    container_name: dropseeker_web_review
    image: ${DOCKER_IMAGE_REVIEW}
    environment:
      VIRTUAL_HOST: review.nextjs.acme.dev
      HTTPS_METHOD: noredirect # support both http and https
      PORT: 3000
    ports:
      - "3000"
    # to get this work with https://github.com/jwilder/nginx-proxy
    # related: https://github.com/jwilder/nginx-proxy/issues/305
    network_mode: bridge
