version: '3'

services:

  dev:
    image: ${DOCKER_IMAGE_DEV:-node:6.10-alpine}
    working_dir: /opt/app
    command: sh run-dev.sh
    environment:
      NODE_ENV: development
      npm_config_tmp: /tmp
      PORT: 3000
      VIRTUAL_HOST: ${VIRTUAL_HOST:-dev.nextjs-hw.acme.dev, ~^dev\.nextjs-hw\..*\.xip\.io}
      VIRTUAL_PORT: 3000
      HTTPS_METHOD: noredirect # support both http and https
    env_file:
      - .env-common
      - .env-dev
    ports:
      - "3000"
    volumes:
      - .:/opt/app
    restart: unless-stopped
    # to get this work with https://github.com/jwilder/nginx-proxy
    # related: https://github.com/jwilder/nginx-proxy/issues/305
    network_mode: bridge
